/* do not change this file, it is auto generated by storybook. */

import { start, updateView } from '@storybook/react-native';

import '@storybook/addon-ondevice-controls/register';
import '@storybook/addon-ondevice-actions/register';
import '@storybook/addon-ondevice-backgrounds/register';
import '@storybook/addon-ondevice-notes/register';

const normalizedStories = [
  {
    titlePrefix: '',
    directory: '../src',
    files: '**/*.stories.?(ts|tsx)',
    importPathMatcher:
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx)?)$/,
    // @ts-ignore
    req: require.context(
      '../src',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx)?)$/,
    ),
  },
];

declare global {
  // eslint-disable-next-line no-var
  var view: ReturnType<typeof start>;
  // eslint-disable-next-line no-var
  var STORIES: typeof normalizedStories;
}

const annotations = [
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  require('./preview'),
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  require('@storybook/react-native/dist/preview'),
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  require('@storybook/addon-ondevice-actions/preview'),
];

global.STORIES = normalizedStories;

// @ts-ignore
module?.hot?.accept?.();

if (!global.view) {
  global.view = start({
    annotations,
    storyEntries: normalizedStories,
  });
} else {
  updateView(global.view, annotations, normalizedStories);
}

export const view = global.view;
